= 디스크립터 세트 레이아웃과 버퍼 (Descriptor set layout and buffer)
include::../common/header.adoc[]
:imagesdir!:

== 개요 (Introduction)

이제 정점마다 원하는 속성을 정점 셰이더에 전달할 수 있게 되었습니다. 그렇다면 전역 변수는 어떻게 처리해야 할까요? 이번 장부터는 3D 그래픽스를 다루기 때문에 모델-뷰-투영(MVP) 행렬이 꼭 필요합니다. 이 행렬을 정점 데이터에 포함할 수도 있지만, 이는 메모리 낭비일 뿐만 아니라 변환이 바뀔 때마다 정점 버퍼를 계속 업데이트해야 하는 문제가 생깁니다. 게다가 이런 변환은 매 프레임마다 아주 쉽게 바뀔 수 있습니다.

Vulkan에서 이 문제를 해결하는 올바른 방법은 바로 리소스 디스크립터(Descriptor)를 사용하는 것입니다. 디스크립터는 셰이더가 버퍼나 이미지 같은 리소스에 자유롭게 접근할 수 있도록 해주는 매개체입니다. 우리는 변환 행렬이 담긴 버퍼를 하나 만들고, 정점 셰이더가 디스크립터를 통해 이 버퍼에 접근하도록 설정할 것입니다. 디스크립터를 사용하는 과정은 크게 다음 세 단계로 나뉩니다.

* 파이프라인을 생성할 때 디스크립터 세트 레이아웃 지정하기
* 디스크립터 풀에서 디스크립터 세트 할당받기
* 렌더링할 때 디스크립터 세트 바인딩하기

디스크립터 세트 레이아웃은 렌더 패스가 접근할 첨부물(Attachment)의 종류를 지정하는 것처럼, 파이프라인이 접근할 리소스의 타입을 정의합니다. 그리고 디스크립터 세트는 프레임버퍼가 렌더 패스 첨부물에 실제 이미지 뷰를 연결하는 것처럼, 디스크립터에 바인딩할 실제 버퍼나 이미지 리소스를 지정합니다. 이렇게 준비된 디스크립터 세트는 정점 버퍼나 프레임버퍼처럼 그리기 명령 단계에서 바인딩되어 사용됩니다.

디스크립터에는 여러 종류가 있지만, 이번 장에서는 유니폼 버퍼 오브젝트(UBO)를 살펴보겠습니다. 다른 종류의 디스크립터는 앞으로의 장에서 다루겠지만 기본적인 사용 흐름은 모두 같습니다. 정점 셰이더에 전달하고 싶은 데이터가 다음과 같은 C 언어 구조체 형태로 준비되어 있다고 가정해 봅시다.

[source,cpp]
----
struct UniformBufferObject {
    glm::mat4 model;
    glm::mat4 view;
    glm::mat4 proj;
}
----

그 다음 데이터를 {VkBuffer}[``VkBuffer``]로 복사하면, 정점 셰이더에서 유니폼 버퍼 오브젝트 디스크립터를 통해 다음과 같이 데이터에 접근할 수 있습니다.

[source,glsl]
----
layout(binding = 0) uniform UniformBufferObject{
    mat4 model;
    mat4 view;
    mat4 proj;
} ubo;

void main() {
    gl_Position = ubo.proj * ubo.view * ubo.model * vec4(inPosition, 0.0, 1.0);
    flagColor = inColor;
}
----

우리는 이전 장에서 만든 사각형을 3D 공간에서 회전시키기 위해, 매 프레임마다 모델, 뷰, 투영 행렬을 업데이트할 예정입니다.

== 정점 셰이더 (Vertex shader)

정점 셰이더를 수정하여 위에서 정의한 유니폼 버퍼 오브젝트를 포함하도록 하겠습니다. 여러분이 MVP 변환에 이미 익숙하다고 가정하고 진행하겠습니다. 만약 이 개념이 생소하시다면, 첫 번째 장에서 언급한 link:https://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/[참고 자료]를 확인해 주세요.

[source,glsl]
----
#version 450

layout(binding = 0) uniform UniformBufferObject {
    mat4 model;
    mat4 view;
    mat4 proj;
} ubo;
layout(location = 0) in vec2 inPosition;
layout(location = 1) in vec3 inColor;
layout(location = 0) out vec3 fragColor;

void main() {
    gl_Position = ubo.proj * ubo.view * ubo.model * vec4(inPosition, 0.0, 1.0);
    fragColor = inColor;
}
----

참고로 ``uniform``, ``in``, ``out`` 선언 순서는 결과에 영향을 주지 않습니다. binding 지시자는 속성에 사용했던 location 지시자와 비슷한 역할을 합니다. 우리는 이 바인딩 번호를 디스크립터 세트 레이아웃에서 참조할 예정입니다. gl_Position이 포함된 줄은 행렬 변환을 거쳐 클립 좌표계 기준의 최종 위치를 계산하도록 변경되었습니다. 2D 삼각형을 그릴 때와 달리, 클립 좌표의 마지막 성분(W 값)이 1이 아닐 수 있습니다. 이는 화면의 최종 정규화 장치 좌표(NDC)로 변환되는 과정에서 나눗셈 연산으로 이어집니다. 투영 변환에서는 이를 '원근 분할'이라고 부르며, 가까운 물체는 크게 보이고 멀리 있는 물체는 작게 보이도록 만드는 핵심 원리입니다.

== 디스크립터 세트 레이아웃 (Descriptor set layout)

다음 단계는 C++ 코드에서 UBO를 정의하고, 정점 셰이더에 있는 이 디스크립터의 존재를 Vulkan에 알리는 것입니다.

[source,cpp]
----
struct UniformBufferObject {
    glm::mat4 model;
    glm::mat4 view;
    glm::mat4 proj;
};
----

GLM에서 제공하는 데이터 타입을 사용하면 셰이더에 선언된 구조체와 완전히 똑같이 매칭할 수 있습니다. 이 행렬 데이터들은 셰이더가 요구하는 바이너리 구조와 완벽히 호환되므로, 나중에 ``UniformBufferObjec``t의 내용을 memcpy를 통해 {VkBuffer}[``VkBuffer``]로 그대로 복사하기만 하면 됩니다.

모든 정점 속성과 그 로케이션(``location``) 인덱스를 설정했던 것처럼, 파이프라인을 생성할 때도 셰이더에서 사용하는 모든 디스크립터 바인딩에 대한 상세 정보를 제공해야 합니다. 이 모든 정보를 정의하기 위해 ``createDescriptorSetLayout``이라는 새로운 함수를 만들겠습니다. 이 레이아웃 정보는 파이프라인 생성 시점에 꼭 필요하므로, 파이프라인을 만들기 직전에 이 함수를 호출해야 합니다.

[source,cpp]
----
void initVulkan() {
    ...
    createDescriptorSetLayout();
    createGraphicsPipeline();
    ...
}
...
void createDescriptorSetLayout() {
    
}
----

각각의 바인딩 정보는 {VkDescriptorSetLayoutBinding}[``VkDescriptorSetLayoutBinding``] 구조체를 통해 작성합니다.

[source,cpp]
----
void createDescriptorSetLayout() {
    VkDescriptorSetLayoutBinding uboLayoutBinding{
        .binding = 0,
        .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
        .descriptorCount = 1,
    };
}
----

처음 두 필드는 셰이더에서 지정한 바인딩 번호와 디스크립터의 타입(여기서는 유니폼 버퍼 오브젝트)을 지정합니다. 셰이더 변수를 유니폼 버퍼 오브젝트의 배열 형태로 선언할 수도 있는데, ``descriptorCount``는 이 배열의 원소 개수를 의미합니다. 예를 들어 스켈레탈 애니메이션을 구현할 때 뼈대마다 각각의 변환 행렬을 전달하기 위해 이를 활용할 수 있습니다. 우리가 사용할 MVP 변환은 단 하나의 유니폼 버퍼 오브젝트에 들어가므로 descriptorCount를 ``1``로 설정합니다.

[source,cpp]
----
uboLayoutBinding.stageFlags = VK_SHADER_STAGE_VERTEX_BIT;
----

또한 이 디스크립터를 어느 셰이더 단계(Stage)에서 참조할 것인지도 지정해야 합니다. ``stageFlags`` 필드에는 {VkShaderStageFlagBits}[``VkShaderStageFlagBits``] 값들을 조합하거나 ``VK_SHADER_STAGE_ALL_GRAPHICS``를 사용할 수 있습니다. 우리의 경우, 정점 셰이더에서만 이 디스크립터를 참조하므로 정점 셰이더 플래그만 지정합니다.

[source,cpp]
----
uboLayoutBinding.pImmutableSamplers = nullptr;  // Optional
----

``pImmutableSamplers`` 필드는 이미지 샘플링과 관련된 디스크립터에서만 사용되는 항목으로, 나중에 자세히 살펴보겠습니다. 지금은 기본값(nullptr)으로 채워두시면 됩니다.

설정한 모든 디스크립터 바인딩들은 하나의 {VkDescriptorSetLayout}[``VkDescriptorSetLayout``] 오브젝트로 묶이게 됩니다. ``pipelineLayout`` 변수 바로 위에 새로운 클래스 멤버 변수를 정의해 줍니다.

[source,cpp]
----
VkDescriptorSetLayout _descriptorSetLayout;
VkPipelineLayout _pipelineLayout;
----

그 다음 {vkCreateDescriptorSetLayout}[``vkCreateDescriptorSetLayout``] 함수를 이용해 이 오브젝트를 생성할 수 있습니다. 이 함수는 앞서 만든 바인딩 배열 정보가 담긴 단순한 {VkDescriptorSetLayoutCreateInfo}[``VkDescriptorSetLayoutCreateInfo``] 구조체를 인자로 받습니다.

[source,cpp]
----
VkDescriptorSetLayoutCreateInfo layoutInfo{
    .sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
    .bindingCount = 1,
    .pBindings = &uboLayoutBinding,
};

if (vkCreateDescriptorSetLayout(_device, &layoutInfo, nullptr, &_descriptorSetLayout) != VK_SUCCESS) {
    throw std::runtime_error("failed to create descriptor set layout!");
}
----

파이프라인을 생성할 때 셰이더가 어떤 디스크립터들을 사용할지 Vulkan에 알려주려면 이 디스크립터 세트 레이아웃을 지정해야 합니다. 디스크립터 세트 레이아웃은 파이프라인 레이아웃 오브젝트 안에서 지정합니다. {VkPipelineLayoutCreateInfo}[``VkPipelineLayoutCreateInfo``] 구조체를 수정하여 우리가 만든 레이아웃 오브젝트를 참조하도록 변경해 줍니다.

[source,cpp]
----
// void createGraphicsPipeline 함수
VkPipelineLayoutCreateInfo pipelineLayoutInfo{
    .sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
    .setLayoutCount = 1,
    .pSetLayouts = &_descriptorSetLayout,
};
----

레이아웃 하나만으로도 모든 바인딩 정보를 다 담을 수 있는데, 왜 여기서 여러 개의 디스크립터 세트 레이아웃을 지정할 수 있게 해두었는지 의아할 수 있습니다. 이 의문은 다음 장에서 디스크립터 풀과 디스크립터 세트를 다루면서 함께 풀어보겠습니다.

디스크립터 세트 레이아웃은 새로운 그래픽스 파이프라인을 다시 생성하는 동안에도 계속 유지되어야 하므로, 프로그램이 완전히 종료될 때 해제해야 합니다.

[source,cpp]
----
void cleanup() {
    cleanupSwapChain();

    vkDestroyDescriptorSetLayout(_device, _descriptorSetLayout, nullptr);
    ...
}
----

== 유니폼 버퍼 (Uniform buffer)

다음 장에서는 셰이더에 UBO 데이터를 전달할 버퍼를 직접 지정하겠지만, 그 전에 먼저 이 버퍼를 생성해야 합니다. 우리는 매 프레임마다 유니폼 버퍼에 새로운 데이터를 복사할 예정이므로, 스테이징 버퍼(Staging Buffer)를 사용하는 것은 의미가 없습니다. 이 경우에는 오히려 불필요한 오버헤드만 늘어나고, 성능 향상은커녕 도리어 성능이 떨어질 가능성이 높습니다.

또한 우리는 여러 개의 버퍼를 확보해야 합니다. 동시에 여러 프레임이 처리 중(In-Flight)일 수 있기 때문인데, 이전 프레임이 여전히 버퍼를 읽고 있는 와중에 다음 프레임을 준비하겠다고 버퍼를 업데이트해서는 안 되기 때문입니다! 따라서 동시에 처리할 수 있는 최대 프레임 수만큼 유니폼 버퍼를 만들어 두고, GPU가 현재 읽고 있지 않은 유니폼 버퍼에 데이터를 써야 합니다.

이를 위해 ``uniformBuffers``와 ``uniformBuffersMemory``를 위한 새로운 클래스 멤버 변수를 추가해 줍니다.

[source,cpp]
----
VkBuffer _indexBuffer;
VkDeviceMemory _indexBufferMemory;

std::vector<VkBuffer> _uniformBuffers;
std::vector<VkDeviceMemory> _uniformBuffersMemory;
std::vector<void*> _uniformBufferMapped;
----

마찬가지로 ``createIndexBuffer`` 호출 직후에 실행되어 버퍼들을 할당할 새로운 함수인 ``createUniformBuffers``를 생성합니다.

[source,cpp]
----
void initVulkan() {
    ...
    createVertexBuffer();
    createIndexBuffer();
    createUniformBuffers();
    ...
}
...
void createUniformBuffers() {
    VkDeviceSize bufferSize = sizeof(UniformBufferObject);

    _uniformBuffers.resize(MAX_FRAMES_IN_FLIGHT);
    _uniformBuffersMemory.resize(MAX_FRAMES_IN_FLIGHT);
    _uniformBuffersMapped.resize(MAX_FRAMES_IN_FLIGHT);

    for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
        createBuffer(bufferSize, VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
                        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT, _uniformBuffers[i],
                        _uniformBuffersMemory[i]);

        vkMapMemory(_device, _uniformBuffersMemory[i], 0, bufferSize, 0, &_uniformBuffersMapped[i]);
    }
}
----

버퍼를 생성한 직후에는 {vkMapMemory}[``vkMapMemory``]를 사용해 메모리를 매핑해 둠으로써, 나중에 데이터를 작성할 때 사용할 포인터를 미리 얻어옵니다. 이 버퍼는 애플리케이션의 수명이 다할 때까지 매핑된 포인터 상태를 그대로 유지하게 됩니다. 이 기법을 "지속적 매핑(**Persistent Mapping**)"이라고 부르며, 모든 Vulkan 구현체에서 완벽하게 지원됩니다. 매핑 작업은 비용이 들기 때문에, 데이터를 업데이트할 때마다 매번 버퍼를 매핑하지 않아도 되므로 성능이 크게 향상됩니다.

유니폼 데이터는 모든 그리기 명령(Draw Call)에서 공통으로 사용되므로, 이를 담은 버퍼는 렌더링을 완전히 중단할 때만 해제해야 합니다.

[source,cpp]
----
void cleanup() {
    ...
    for (size_t i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
        vkDestroyBuffer(_device, _uniformBuffers[i], nullptr);
        vkFreeMemory(_device, _uniformBuffersMemory[i], nullptr);
    }

    vkDestroyDescriptorSetLayout(_device, _descriptorSetLayout, nullptr);
}
----

== 유니폼 데이터 업데이트하기 (Updating uniform data)

새로운 함수 ``updateUniformBuffer``를 만들고, 다음 프레임을 제출(Submit)하기 전 ``drawFrame`` 함수에서 이 함수를 호출하도록 코드를 추가합니다.

[source,cpp]
----
void drawFrame() {
    ...
    updateUniformBuffer(currentFrame);
    ...

    VkSubmitInfo submitInfo{
        .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
        .waitSemaphoreCount = 1,
        .pWaitSemaphores = waitSemaphores,
        .pWaitDstStageMask = waitStages,
        .commandBufferCount = 1,
        .pCommandBuffers = &_commandBuffers[currentFrame],
        .signalSemaphoreCount = 1,
        .pSignalSemaphores = signalSemaphores,
    };
    ...
}
...
void updateUniformBuffer(uint32_t currentImage) {

}
----

이 함수는 도형이 회전할 수 있도록 매 프레임마다 새로운 변환 행렬을 생성합니다. 이 기능을 구현하려면 다음 두 개의 헤더를 새로 포함해야 합니다.

[source,cpp]
----
#define GLM_FORCE_RADIANS
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#include <chrono>
----

``glm/gtc/matrix_transform.hpp`` 헤더는 모델 변환을 위한 ``glm::rotate``, 뷰 변환을 위한 ``glm::lookAt``, 투영 변환을 위한 ``glm::perspective`` 같은 행렬 생성 함수들을 제공합니다. ``GLM_FORCE_RADIANS`` 정의는 ``glm::rotate`` 같은 함수들이 인자로 각도(Degree) 대신 라디안(Radian)을 확실하게 사용하도록 강제하여, 발생할 수 있는 혼선을 방지하는 데 꼭 필요합니다.

C++ 표준 라이브러리의 ``chrono`` 헤더는 정밀한 시간 측정을 위한 함수들을 제공합니다. 이를 활용하면 프레임 레이트(FPS)에 상관없이 도형이 초당 90도씩 일정한 속도로 회전하도록 만들 수 있습니다.

[source,cpp]
----
void updateUniformBuffer(uint32_t currentImage) {
    static auto startTime = std::chrono::high_resolution_clock::now();
    auto currentTime = std::chrono::high_resolution_clock::now();
    float time = std::chrono::duration<float, std::chrono::seconds::period>(currentTime - startTime).count();
}
----

``updateUniformBuffer`` 함수는 먼저 렌더링이 시작된 이후 흘러간 시간을 부동소수점 정밀도의 초(Second) 단위로 계산하는 로직으로 시작합니다.

이제 유니폼 버퍼 오브젝트에 들어갈 모델, 뷰, 투영 변환을 정의하겠습니다. 모델 변환은 앞서 계산한 시간 변수(``time``)를 활용하여 Z축을 중심으로 간단히 회전하도록 구현합니다.

[source,cpp,linenums]
----
UniformBufferObject ubo{
    .model = glm::rotate(glm::mat4(1.0f), time * glm::radians(90.0f), glm::vec3(0.0f, 0.0f, 1.0f)),
    .view = glm::lookAt(glm::vec3(2.0f, 2.0f, 2.0f), glm::vec3(0.0f, 0.0f, 0.0f), glm::vec3(0.0f, 0.0f, 1.0f)),
    .proj = glm::perspective(glm::radians(45.0f), _swapChainExtent.width / (float)_swapChainExtent.height, 0.1f,
                                10.0f),
};
----

``glm::rotate`` 함수는 기존 변환 행렬, 회전 각도, 회전축을 인자로 받습니다. ``glm::mat4(1.0f)`` 생성자는 단위 행렬을 반환합니다. 회전 각도로 ``time * glm::radians(90.0f)``를 사용하면 초당 90도씩 회전한다는 목적을 달성할 수 있습니다(**2번라인**).

뷰 변환의 경우, 도형을 위쪽 45도 각도에서 내려다보도록 설정했습니다. ``glm::lookAt`` 함수는 카메라의 위치(정점), 바라보는 중심점, 그리고 카메라의 상단 위쪽(Up) 방향 벡터를 인자로 받습니다(**3번라인**).

투영 변환은 수직 시야각(FOV) 45도의 원근 투영을 선택했습니다. 나머지 인자로는 종횡비(Aspect Ratio), 그리고 근평면(Near)과 원평면(Far) 값을 넘겨줍니다. 창 크기가 조절된 후의 새로운 가로, 세로 길이를 제대로 반영할 수 있도록, 현재 스왑 체인의 익스텐트(Extent) 크기를 가져와 종횡비를 계산하는 것이 중요합니다(**4번라인**).

[source,cpp]
----
ubo.proj[1][1] *= -1;
----

GLM은 원래 클립 좌표계의 Y축이 뒤집혀 있는 OpenGL을 기반으로 설계되었습니다. Vulkan에서 이를 보정하는 가장 쉬운 방법은 투영 행렬에서 Y축 스케일링 성분의 부호를 반대로 바꾸는 것입니다. 이 작업을 해주지 않으면 화면에 이미지가 거꾸로 뒤집혀서 렌더링됩니다.

모든 변환 행렬이 정의되었으므로, 이제 유니폼 버퍼 오브젝트의 데이터를 현재 프레임에 해당하는 유니폼 버퍼로 복사하면 됩니다. 이 과정은 정점 버퍼 때와 완전히 같지만, 스테이징 버퍼를 거치지 않는다는 점만 다릅니다. 앞서 언급했듯이 유니폼 버퍼는 처음 한 번만 매핑해 두므로, 매번 다시 매핑할 필요 없이 데이터 포인터에 직접 값을 쓸 수 있습니다.

[source,cpp]
----
memcpy(_uniformBuffersMapped[currentImage], &ubo, sizeof(ubo));
----

사실 이렇게 자주 바뀌는 값을 셰이더에 전달할 때 UBO를 쓰는 것이 가장 효율적인 방법은 아닙니다. 크기가 작은 데이터 버퍼를 셰이더에 전달할 때는 푸시 콘스탄트(Push Constants)를 사용하는 것이 훨씬 효율적입니다. 이 기법은 앞으로의 장에서 기회가 되면 살펴보겠습니다.

link:./DescriptorPoolAndSets.html[다음 장]에서는 셰이더가 이 변환 데이터에 실제로 접근할 수 있도록, VkBuffer를 유니폼 버퍼 디스크립터에 연결해 주는 디스크립터 세트(Descriptor Sets)에 대해 알아보겠습니다.