= 마치며 (Conclusion)
include::../common/header.adoc[]
:imagesdir!:

이제 지난 장들에서 다룬 모든 구조와 객체를 결합하여 그래픽 파이프라인을 만들 수 있습니다! 간단히 정리하자면, 현재 우리가 가지고 있는 객체의 유형은 다음과 같습니다:

* 셰이더 스테이지: 그래픽 파이프라인의 프로그래밍 가능한 스테이지의 기능을 정의하는 셰이더 모듈
* 고정 기능 스테이트: 입력 어셈블리, 래스터라이저, 뷰포트, 컬러 블렌딩 등 파이프라인의 고정 기능 스테이지를 정의하는 모든 구조체
* 파이프라인 레이아웃: 셰이더에서 참조하며 렌더링 시점에 업데이트될 수 있는 유니폼 및 푸시 값
* 렌더 패스: 파이프라인 스테이지에서 참조하는 어태치먼트와 그 사용법

이 모든 요소가 결합되어 그래픽 파이프라인의 기능을 완전히 정의하므로, 이제 ``createGraphicsPipeline`` 함수의 마지막 부분에서 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkGraphicsPipelineCreateInfo.html[``VkGraphicsPipelineCreateInfo``] 구조체를 채우기 시작할 수 있습니다. 하지만 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkDestroyShaderModule.html[``vkDestroyShaderModule``] 호출은 생성 과정에서 여전히 사용될 예정이므로, 이 단계에서는 호출하지 않아야 합니다.

[source,cpp]
----
VkGraphicsPipelineCreateInfo pipelineInfo{
    .sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
    .pNext = nullptr,
    .stageCount = 2,
    .pStage = shaderStages,
};
----

먼저 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPipelineShaderStageCreateInfo.html[``VkPipelineShaderStageCreateInfo``] 구조체 배열을 참조합니다.

[source,cpp]
----
pipelineInfo.pVertexInputState = &vertexInputInfo;
pipelineInfo.pInputAssemblyState = &inputAssembly;
pipelineInfo.pViewportState = &viewportState;
pipelineInfo.pRasterizationState = &rasterizer;
pipelineInfo.pMultisampleState= &multiSampling;
pipelineInfo.pDepthStencilState = nullptr; // Optional
pipelineInfo.pColorBlendState = &colorBlending;
pipelineInfo.pDyanmicState = &dynamicState;
----

그런 다음 고정 기능 단계를 설명하는 모든 구조를 참조합니다.

[source,cpp]
----
pipelineInfo.layout = _pipelineLayout;
----

그 다음에는 파이프라인 레이아웃이 나오는데, 이는 구조체 포인터가 아니라 {vk} 핸들입니다.

[source,cpp]
----
pipelineInfo.renderPass = _renderPass;
pipelineInfo.subpass = 0;
----

마지막으로, 이 그래픽 파이프라인이 사용될 렌더 패스와 서브 패스의 인덱스에 대한 참조가 있습니다. 이 특정 인스턴스 대신 다른 렌더 패스를 이 파이프라인과 함께 사용할 수도 있지만, 해당 렌더 패스는 ``_renderPass``와 호환되어야 합니다. 호환성 요건은 link:https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/chap8.html#renderpass-compatibility[여기]에서 설명되어 있지만, 이 튜토리얼에서는 해당 기능을 사용하지 않을 것입니다.

[source,cpp]
----
pipelineInfo.basePipelineHandle = VK_NULL_HANDLE; // Optional
pipelineInfo.basePipelineIndex = -1; // Optional
----

NOTE: link:../Drawing/Framebuffers.html[Framebuffers로 이동]