= 렌더 패스 (Render passes)
include::../common/header.adoc[]
:imagesdir!:

== 설정 (Setup)

파이프라인 생성을 완료하기 전에, 렌더링 중에 사용될 프레임버퍼 어태치먼트에 대해 Vulkan에 알려야 합니다. 컬러 버퍼와 뎁스 버퍼의 개수, 각 버퍼에 사용할 샘플 수, 그리고 렌더링 작업 전반에 걸쳐 해당 버퍼의 내용을 어떻게 처리할지 지정해야 합니다. 이 모든 정보는 렌더 패스 객체에 포함되며, 이를 위해 새로운 ``createRenderPass`` 함수를 생성할 것입니다. 이 함수는 ``createGraphicsPipeline``을 호출하기 전에 ``initVulkan``에서 호출해야 합니다.

[source,cpp]
----
void initVulkan() {
    createInstance();
    setupDebugMessenger();
    createSurface();
    pickPhysicalDevice();
    createLogicalDevice();
    createSwapChain();
    createImageViews();
    createRenderPass();
    createGraphicsPipeline();
}
...
void createRenderPass() {

}
----

== 첨부파일 설정 (Attachment description)

이 경우, 스왑 체인의 이미지 중 하나로 표현되는 단일 컬러 버퍼 첨부 파일만 사용하게 됩니다.

[source,cpp]
----
void createRenderPass() {
    VkAttachmentDescription colorAttachment{
        .format = _swapChainImageFormat,
        .samples = VK_SAMPLE_COUNT_1_BIT,
    };
}
----

``loadOp``와 ``storeOp``는 렌더링 전과 렌더링 후 어태치먼트(attachment)의 데이터를 어떻게 처리할지 결정합니다. ``loadOp``에는 다음과 같은 옵션이 있습니다:

[cols="4a,6",options=header]
|===
|플래그
|설명

|``VK_ATTACHMENT_LOAD_OP_LOAD``
|어태치먼트의 기존 내용을 유지합니다.

|``VK_ATTACHMENT_LOAD_OP_CLEAR``
|시작 시 값을 상수 값으로 초기화합니다.

|``VK_ATTACHMENT_LOAD_OP_DONT_CARE``
|기존 내용은 정의되지 않으며, 이를 고려하지 않음
|===

이 경우, 새로운 프레임을 그리기 전에 프레임버퍼를 검은색으로 지우기 위해 clear 연산을 사용할 것입니다. ``storeOp``에는 다음 두 가지 옵션만 있습니다:

NOTE: ``VkAttachmentStoreOp`` 모든 열거형 정리

[cols="4a,6",options=header]
|===
|플래그
|설명

|``VK_ATTACHMENT_STORE_OP_STORE``
|렌더링 패스 중에 생성된 내용과 렌더링 영역 내의 내용이 메모리에 기록되도록 지정합니다. 깊이/스텐실 형식을 가진 어태치먼트의 경우, 이 옵션은 ``VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT`` 액세스 유형을 사용합니다. 컬러 형식의 어태치먼트의 경우, 이 함수는 ``VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT`` 액세스 유형을 사용합니다.

|``VK_ATTACHMENT_STORE_OP_DONT_CARE``
|렌더링 영역 내의 내용이 렌더링 후 필요하지 않으며 버려질 수 있음을 지정하며, 렌더링 영역 내의 어태치먼트 내용은 정의되지 않습니다. 깊이/스텐실 형식의 어태치먼트의 경우, 이 함수는 ``VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT`` 액세스 유형을 사용합니다. 색상 형식의 어태치먼트의 경우, 이 함수는 ``VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT`` 액세스 유형을 사용합니다.

|``VK_ATTACHMENT_STORE_OP_NONE``
``VK_ATTACHMENT_STORE_OP_NONE_KHR``
``VK_ATTACHMENT_STORE_OP_NONE_QCOM``
``VK_ATTACHMENT_STORE_OP_NONE_EXT``
|렌더링 패스 중에 어태치먼트에 값이 쓰여지지 않는 한, 스토어 연산에 의해 렌더 영역 내의 콘텐츠에 접근하지 않음을 지정합니다. 렌더링 패스 중에 값이 쓰여지는 경우, 이는 ``VK_ATTACHMENT_STORE_OP_DONT_CARE``와 동일하게 동작하며, 이에 상응하는 액세스 세미언틱을 갖습니다.

**v1.3부터 사용 가능**
|===

화면에 렌더링된 삼각형을 확인하고자 하므로, 여기서는 저장 작업을 선택합니다.

[source,cpp]
----
colorAttachment.stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
colorAttachment.stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
----

``loadOp`` 및 ``storeOp``는 색상 및 심도 데이터에 적용되며, ``stencilLoadOp`` 및 ``stencilStoreOp``는 스텐실 데이터에 적용됩니다. 본 애플리케이션에서는 스텐실 버퍼를 전혀 사용하지 않으므로, 스텐실 버퍼의 로드 및 저장 결과는 중요하지 않습니다.

[source,cpp]
----
colorAttachment.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
colorAttachment.finalLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
----

{vk}에서 텍스처와 프레임버퍼는 특정 픽셀 형식을 가진 {VkImage}[``VkImage``] 객체로 표현되지만, 메모리 내 픽셀의 배열은 이미지를 어떻게 활용하느냐에 따라 달라질 수 있습니다.

가장 일반적인 배열로는 다음과 같은 것들이 있습니다.

[cols="4a,6",options=header]
|===
|플래그
|설명

|``VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL``
|색상 참고용으로 사용된 이미지

|``VK_IMAGE_LAYOUT_PRESENT_SRC_KHR``
|스왑 체인에 표시될 이미지

|``VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL``
|메모리 복사 작업의 대상으로 사용될 이미지
|===

NOTE: link:https://docs.vulkan.org/refpages/latest/refpages/source/VkImageLayout.html[VkImageLayout] 참고

이 주제에 대해서는 텍스처링 장에서 더 자세히 다루겠지만, 지금 당장 알아두어야 할 중요한 점은 이미지가 향후 수행될 작업에 적합한 특정 레이아웃으로 변환되어야 한다는 것입니다.

``initialLayout``은 렌더링 패스가 시작되기 전 이미지의 레이아웃을 지정합니다. ``finalLayout``은 렌더링 패스가 완료되었을 때 자동으로 전환될 레이아웃을 지정합니다. ``initialLayout``에 ``VK_IMAGE_LAYOUT_UNDEFINED``를 사용하면 이미지가 이전에 어떤 레이아웃이었는지는 중요하지 않음을 의미합니다. 이 특수 값의 단점은 이미지의 내용이 보존된다는 보장이 없다는 점이지만, 어차피 이미지를 지울 예정이므로 이는 문제가 되지 않습니다. 렌더링 후 스왑 체인을 사용하여 이미지를 바로 표시할 수 있도록 준비해야 하므로, ``finalLayout``으로 ``VK_IMAGE_LAYOUT_PRESENT_SRC_KHR``을 사용합니다.

== 하위 패스 및 첨부 참조 (Subpasses and attachment references)

단일 렌더링 패스는 여러 개의 서브패스로 구성될 수 있습니다. 서브패스는 이전 패스의 프레임버퍼 내용에 의존하는 후속 렌더링 작업으로, 예를 들어 차례로 적용되는 일련의 후처리 효과 등을 말합니다. 이러한 렌더링 작업을 하나의 렌더링 패스로 묶으면, {vk}은 작업 순서를 재조정하여 메모리 대역폭을 절약함으로써 성능을 향상시킬 수 있습니다. 하지만 우리가 처음 그릴 삼각형의 경우에는 단일 서브패스로만 진행하겠습니다.

모든 서브패스는 앞선 섹션에서 설명한 구조를 사용하여 정의한 하나 이상의 어태치먼트를 참조합니다. 이러한 참조는 다음과 같은 형태의 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAttachmentReference.html[``VkAttachmentReference``] 구조체입니다:

[source,cpp]
----
VkAttachmentReference colorAttachmentRef{
    .attachment = 0,
    .layout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
};
----

``attachment`` 매개변수는 attachment descriptions 배열 내의 인덱스를 통해 참조할 attachment를 지정합니다. 이 배열은 단일 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAttachmentDescription.html[``VkAttachmentDescription``]으로 구성되어 있으므로 인덱스는 ``0``입니다. ``layout``은 이 참조를 사용하는 서브패스(subpass) 동안 attachment가 가질 레이아웃을 지정합니다. {vk}은 서브패스가 시작될 때 attachment를 자동으로 이 레이아웃으로 전환합니다. 우리는 이 어태치먼트를 컬러 버퍼로 사용할 계획이며, 이름에서 알 수 있듯이 ``VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL`` 레이아웃이 최상의 성능을 제공할 것입니다.

서브패스는 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSubpassDescription.html[``VkSubpassDescription``] 구조체를 사용하여 정의됩니다:

[source,cpp]
----
VkSubpassDescription subpass{
    .pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS,
};
----

{vk}은 향후 컴퓨트 서브패스를 지원할 수도 있으므로, 이번 작업이 그래픽 서브패스임을 명확히 명시해야 합니다. 다음으로, 컬러 어태치먼트에 대한 참조를 지정합니다:

[source,cpp]
----
subpass.colorAttachmentCount = 1;
subpass.pColorAttachments = &colorAttachmentRef;
----

이 배열에 포함된 어태치먼트의 인덱스는 프래그먼트 셰이더에서 ``layout(location = 0) out vec4 outColor`` 지시어를 통해 직접 참조됩니다!

서브패스에서는 다음과 같은 다른 유형의 어태치먼트도 참조할 수 있습니다:

[cols="4a,6",options=header]
|===
|멤버필드
|설명

|``pInputAttachments``
|셰이더에서 읽어오는 첨부 파일

|``pResolveAttachments``
|멀티샘플링 컬러 어태치먼트에 사용되는 어태치먼트

|``pDepthStencilAttachment``
|깊이 및 스텐실 데이터용 첨부 파일

|``pPreserveAttachments``
|이 하위 패스에서 사용되지는 않지만, 데이터는 보존되어야 하는 첨부 파일
|===

== 렌더 패스 (Render passes)

어태치먼트와 이를 참조하는 기본 서브패스에 대해 설명했으므로, 이제 렌더 패스 자체를 생성할 수 있습니다. ``pipelineLayout`` 변수 바로 위에 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkRenderPass.html[``VkRenderPass``] 객체를 담을 새로운 클래스 멤버 변수를 생성하세요:

[source,cpp]
----
VkRenderPass _renderPass;
VkPipelineLayout _pipelineLayout;
----

그런 다음 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkRenderPassCreateInfo.html[``VkRenderPassCreateInfo``] 구조체에 어태치먼트와 서브패스의 배열을 입력하여 렌더 패스 객체를 생성할 수 있습니다. link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAttachmentReference.html[``VkAttachmentReference``] 객체는 이 배열의 인덱스를 사용하여 어태치먼트를 참조합니다.

[source,cpp]
----
VkRenderPassCreateInfo renderPassInfo{
    .sType = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO,
    .attachmentCount = 1,
    .pAttachments = &colorAttachment,
    .subpassCount = 1,
    pSubpasses = &subpass,
};

if (vkCreateRenderPass(_device, &renderPassInfo, nullptr, &_renderPass) != VK_SUCCESS) {
    throw std::runtime_error("failed to create render pass!");
}
----

파이프라인 레이아웃과 마찬가지로, 렌더 패스는 프로그램 전반에 걸쳐 참조되므로, 마지막에야 정리해야 합니다:

[source,cpp]
----
void cleanup() {
    vkDestroyPipelineLayout(_device, _pipelineLayout, nullptr);
    vkDestroyRenderPass(_device, _renderPass, nullptr);
    ...
}
----

정말 힘든 작업이었지만, link:./Conclusion.html[다음 장]에서는 이 모든 것이 하나로 어우러져 마침내 그래픽 파이프라인 객체를 완성하게 됩니다!