= 기본코드 (Base code)
include::../common/header.adoc[]

== 일반 구조 (General structure)

이전 장에서는 적절한 구성을 모두 갖춘 {vk} 프로젝트를 만들고 샘플 코드로 테스트했습니다. 이 장에서 우리는 다음 코드로 처음부터 시작합니다.

[source,cpp,linenums]
----
#include <vulkan/vulkan.h>
#include <iostream>
#include <stdexcept>
#include <cstdlib>

class HelloTriangleApplication {
public:
    void run() {
        initVulkan();
        mainLoop();
        cleanup();
    }

private:
    void initVulkan() {}
    void mainLoop() {}
    void cleanup() {}
};

int main() {
    HelloTriangleApplication app;

    try {
        app.run();
    } catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;

        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
----

먼저 기능, 구조 및 열거형을 제공하는 LunarG SDK의 {vk}} 헤더를 포함합니다. ``stdexcept`` 및 ``iostream`` 헤더는 오류를 보고하고 전파하기 위해 포함됩니다. ``cstdlib`` 헤더는 ``EXIT_SUCCESS`` 및 ``EXIT_FAILURE`` 매크로를 제공합니다.

프로그램 자체는 {vk} 개체를 private member로 저장하고 ``initVulkan`` 함수에서 호출되는 기능을 추가하여 각 클래스를 시작하는 클래스로 싸여 있습니다. 모든 것이 준비되면 프레임 렌더링을 시작하기 위해 ``mainLoop``에 들어갑니다. 우리는 ``mainLoop`` 함수를 채워 잠시 후에 window가 닫힐 때까지 반복하는 루프를 포함할 것입니다. Window가 닫히고 ``mainLoop``이 돌아오면 정리 기능에 사용한 리소스를 처리하도록 합니다.

실행 중에 어떤 종류의 치명적인 오류가 발생하면 설명 메시지가 포함 된 ``std::runtime_error`` 예외를 throw하여 ``main`` 함수로 다시 전파되고 명령 프롬프트에 출력됩니다. 다양한 표준 예외 유형도 처리하려면 보다 일반적인 ``std::exception``을 잡습니다. 곧 처리 할 오류의 한 예는 특정 필수 확장이 지원되지 않는다는 것을 알아내는 것입니다.

NOTE: 여기서는 link:https://github.com/gabime/spdlog[spdlog]를 함께 사용할 예정임

이 후에 따르는 대략 모든 장은 ``initVulkan``에서 호출되는 하나의 새로운 기능과 ``cleanup``에서 마지막에 해제되어야 하는 private member에게 하나 이상의 새로운 {vk} 개체를 추가합니다.

== 리소스 관리 (Resource management)

``malloc``으로 할당 된 메모리의 각 덩어리(chunk)가 무료로 호출해야하는 것처럼, 우리가 만드는 모든 Vulkan 개체는 더 이상 필요하지 않을 때 명시 적으로 파괴되어야합니다. C++에서는 <memory> 헤더에 제공된 RAII 또는 스마트 포인터를 사용하여 자동 리소스 관리를 수행할 수 있습니다. 그러나, 저는 이 튜토리얼에서 {vk} 객체의 할당 및 할당에 대해 명시하기로 결정했습니다. 결국 {vk}의 틈새 시장은 실수를 피하기 위해 모든 작업에 대해 명시해야하므로 API가 어떻게 작동하는지 배우기 위해 객체의 수명에 대해 명시하는 것이 좋습니다.

이 자습서를 따르면 {vk} 개체를 생성자에서 획득하고 소멸자에서 내보내는 C++ 클래스를 작성하거나 소유권 요구 사항에 따라 ``std:unique_ptr`` 또는 ``std::shared_ptr``에 사용자 지정 소멸 함수를 제공하여 자동 리소스 관리를 구현할 수 있습니다. RAII는 더 큰 {vk} 프로그램에 권장되는 모델이지만 학습 목적으로는 항상 뒤에서 무슨 일이 일어나고 있는지 아는 것이 좋습니다.

{vk} 개체는 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkCreateXXX.html[``vkCreateXXX``]와 같은 함수로 직접 생성되거나 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkAllocateXXX.html[``vkAllocateXXX``]와 같은 기능을 가진 다른 개체를 통해 할당됩니다. 물체가 더 이상 아무데도 사용되지 않도록 한 후에는 상대방 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkDestroyXXX.html[``vkDestroyXXX``] 및 link:https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkFreeXXX.html[``vkFreeXXX``]와 함께 파괴해야합니다. 이러한 함수의 매개 변수는 일반적으로 다른 유형의 개체에 따라 다르지만 모두 공유하는 매개 변수가 하나 있습니다. ``pAllocator``. 이것은 사용자 지정 메모리 할당자에 대한 콜백을 지정할 수 있는 선택적 매개 변수입니다. 튜토리얼에서이 매개 변수를 무시하고 항상 ``nullptr``을 인수로 전달합니다.

== GLFW 통합 (Integrating GLFW)

{vk}은 오프 스크린 렌더링에 사용하려는 경우 window를 만들지 않고 완벽하게 작동하지만 실제로 무언가를 보여주는 것은 훨씬 더 흥미 롭습니다! 먼저 ``#include <vulkan/vulkan.h>`` 라인을 다음과 같이 교체하십시오.

[source,cpp]
----
#define GLFW_INCLUDE_VULKAN
#include <GFLW/glfw3.h>
----

그렇게 하면 GLFW는 자체 정의를 포함하고 {vk} 헤더를 자동으로 로드합니다. ``initWindow`` 함수를 추가하고 다른 호출 전에 ``run`` 함수에서 호출을 추가합니다. 우리는 그 기능을 사용하여 GLEW를 초기화하고 window를 만들 것입니다.

[source,cpp]
----
    // ...
    void run() {
        initWindow();
        initVulkan();
        mainLoop();
        cleanup();
    }

private:
    void initWindow();
    // ...
----

``initWindow``의 첫 번째 호출은 GLFW 라이브러리를 초기화하는 ``glfwInit()``이어야 합니다. GLFW는 원래 OpenGL 컨텍스트를 생성하도록 설계되었기 때문에 ##후속 호출로 OpenGL 컨텍스트를 만들지 말라##고 해야 합니다.

[source,cpp]
----
glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
----

[TIP]
====
##GLFW_NO_API##는 GLFW 라이브러리에서 윈도우를 생성할 때 OpenGL 등 기본 클라이언트 API context를 생성하지 않도록 지시하는 매크로
====

크기 조정 window를 취급하기 때문에 나중에 살펴볼 특별한주의가 필요하기 때문에 다른 window 힌트 호출로 지금 비활성화하십시오(__Because handling resized windows takes special care that we'll look into later, disable it for now with another window hint call:__).

[source,cpp]
----
glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE)
----

이제 남은 것은 실제 window를 만드는 것입니다. private member를 추가하여 참조를 저장합니다.

[source,cpp]
----
private:
    GLFWwindow* _window;
----

아래의 코드로 window를 초기화 합니다.

[source,cpp]
----
window = glfwCreateWindow(800, 600, "Vulkan", nullptr, nullptr);
//                                            -------  -------
//                                           모니터지정, OpenGL 관련
----

처음 세 매개 변수는 ##window의 너비##, ##높이## 및 ##제목##을 지정합니다. 네 번째 매개 변수를 사용하면 선택적으로 window를 열 ##모니터를 지정##할 수 있으며 마지막 매개 변수는 ##OpenGL과만 관련##이 있습니다.

하드 코딩 된 너비와 높이 숫자 대신 상수를 사용하는 것이 좋습니다. 미래에 이러한 값을 몇 번 언급 할 것이기 때문입니다. ``HelloTriangleApplication`` 클래스 정의 위에 다음 줄을 추가했습니다.

[source,cpp]
----
const uint32_t WIDTH = 800;
const uint32_t HEIGHT = 600;
----

그리고 윈도우 생성 함수의 인자를 위 상수로 변경 합니다.

[source,cpp]
----
_window = glfwCreateWindow(WIDTH, HEIGHT, "Vulkan", nullptr, nullptr);
----

이제 다음과 같은 initWindow 기능을 작성합니다.

[source,cpp]
----
void initWindow() {
    glfwInit();

    glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
    glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);

    _window = glfwCreateWindow(WIDTH, HEIGHT, "Vulkan", nullptr, nullptr);
}
----

오류가 발생하거나 window가 닫힐 때까지 응용 프로그램을 계속 실행하려면 다음과 같이 ``mainLoop`` 함수에 이벤트 루프를 추가해야 합니다.

[source,cpp]
----
void main() {
    while (!glfwWindowShouldClose(_window)) {
        glfwPollEvents();
    }
}
----

이 코드는 상당히 자기 설명이어야합니다. 사용자가 window를 닫을 때까지 프로그램의 종료 이벤트(e.g. 창닫기 버튼, Alt-F4/Windows, CMD-q/macOS)를 반복하고 확인합니다. 이것은 또한 우리가 나중에 단일 프레임을 렌더링하기 위해 함수를 호출하는 루프입니다.

일단 window가 닫히면, 우리는 그것을 파괴하고 GLFW 자체를 종료하여 자원을 정리해야합니다. 다음은 ``cleanup`` 함수의 구현부 입니다.

[source,cpp]
----
void cleanup() {
    glfwDestroyWindow(_window);
    glfwTerminate();
}
----

프로그램을 실행하면 지금 제목이 있는 window가 표시됩니다. 이제 우리는 {vk} 응용 프로그램에 대한 골격, link:./Instance.html[첫 번째 Vulkan 개체를 생성해 봅시다.](_When you run the program now you should see a window titled Vulkan show up until the application is terminated by closing the window. Now that we have the skeleton for the Vulkan application, let's create the first Vulkan object!_)!

.작성자 버전의 전체 소스
[%collapsible]
====
[source,cpp,linenums]
----
//
// Created by JoonHo Son on 2026-05-17.
//
#if !defined(NDEBUG) || defined(_DEBUG)
#define DEBUG_BUILD
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#else
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_INFO
#endif

#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#include <spdlog/spdlog.h>

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/mat4x4.hpp>
#include <glm/vec4.hpp>

const uint32_t WIDTH = 800;
const uint32_t HEIGHT = 600;

class HelloTriangleApplication {
public:
    void run() {
        initWindow();
        initVulkan();
        mainLoop();
        cleanup();
    }

private:
    GLFWwindow* _window;
    void initWindow() {
        glfwInit();
        glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
        glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);

        _window = glfwCreateWindow(WIDTH, HEIGHT, "Vulkan", nullptr, nullptr);
    }

    void initVulkan() {}

    void mainLoop() {
        while (!glfwWindowShouldClose(_window)) {
            glfwPollEvents();
        }
    }

    void cleanup() {
        glfwDestroyWindow(_window);
        glfwTerminate();
    }
};

int main() {
#ifdef DEBUG_BUILD
    spdlog::set_level(spdlog::level::debug);
    spdlog::set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%l] [%s:%#] %v");
#else
    spdlog::set_level(spdlog::level::info);
#endif
    HelloTriangleApplication app;

    try {
        app.run();
    } catch (const std::exception& e) {
        SPDLOG_ERROR("{}", e.what());

        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
----
====