= 물리적 장치 및 큐패밀리 (Physical devices and queue families)
include::../common/header.adoc[]
:imagesdir!:

== 물리적 장치 선택 (Selecting a physical device)

{VkInstance}[``VkInstance``]를 통해 {vk} 라이브러리를 초기화한 후 필요한 기능을 지원하는 시스템에서 그래픽 카드를 찾고 선택해야 합니다. 사실 우리는 그래픽 카드의 번호를 선택하고 동시에 사용할 수 있지만,이 튜토리얼에서는 우리의 요구에 맞는 첫 번째 그래픽 카드를 고수 할 것입니다.

``pickPhysicalDevice`` 함수를 추가하고 ``initVulkan`` 함수에 호출을 추가합니다.

[source,cpp]
----
void initVulkan() {
    createInstance();
    setupDebugMessenger();
    pickPhysicalDevice();
}

void pickPhysicalDevice() {}
----

우리가 선택할 그래픽 카드는 새로운 클래스 멤버로 추가되는 {VkPhysicalDevice}[``VkPhysicalDevice``] 핸들에 저장됩니다. 이 개체는 {VkInstance}[``VkInstance``]가 파괴될 때 암묵적으로 파괴되므로 ``cleanup`` 함수에서 새로운 것을 수행할 필요가 없습니다.

[source,cpp]
----
VkPhysicalDevice _physicalDevice = VK_NULL_HANDLE;
----

그래픽 카드를 나열하는 것은 확장 프로그램을 나열하는 것과 매우 유사하며 숫자만 쿼리하는 것으로 시작합니다.

[source,cpp]
----
uint32_t deviceCount = 0;
vkEnumeratePhysicalDevices(_instance, &deviceCount, nullptr);
----

{vk} 지원 기능이있는 장치가 0 개 있으면 더 멀리 갈 필요가 없습니다.

[source,cpp]
----
if (deviceCount == 0) {
    throw std::runtime_error("failed to find GPUs with Vulkan support!");
}
----

그렇지 않으면 이제 {VkPhysicalDevice}[``VkPhysicalDevice``] 핸들을 모두 보유하기 위해 배열을 할당 할 수 있습니다.

[source,cpp]
----
std::vector<VkPhysicalDevice> devices(deviceCount);
vkEnumeratePhysicalDevices(_instance, &deviceCount, devices.data());
----

이제 우리는 그들 각각을 평가하고 모든 그래픽 카드가 동등하게 생성되는 것은 아니기 때문에 우리가 수행하려는 작업에 적합한지 확인해야 합니다. 이를 위해 우리는 새로운 기능을 소개합니다 :

[source,cpp]
----
bool isDeviceSuitable(VkPhysicalDevice device) {
    return true;
}
----

그리고 물리적 장치 중 하나가 해당 기능에 추가할 요구 사항을 충족하는지 확인합니다.

[source,cpp]
----
for (const auto& device : devices) {
    if (isDeviceSuitable(device)) {
        _physicalDevice = device;
        
        break;
    }
}

if (_physicalDevice == VK_NULL_HANDLE) {
    throw std::runtime_error("failed to find a suitable GPU!");
}
----

다음 섹션에서는 ``isDeviceSuitable`` 함수에서 확인할 첫 번째 요구 사항을 소개합니다. 나중에 챕터에서 더 많은 {vk} 기능을 사용하기 시작할 때 더 많은 검사를 포함하도록 이 기능을 확장합니다.

== 기본 장치 적합성 검사 (Base device suitablility checks)

장치의 적합성을 평가하기 위해 몇 가지 세부 사항을 쿼리하여 시작할 수 있습니다. 이름, 유형 및 지원되는 {vk} 버전과 같은 기본 장치 속성은 {vkGetPhysicalDeviceProperties}[``vkGetPhysicalDeviceProperties``]를 사용하여 쿼리할 수 있습니다.

[source,cpp]
----
VkPhysicalDeviceProperties deviceProperties;
vkGetPhysicalDeviceProperties(device, &deviceProperties);
----

텍스처 압축, 64 비트 플로트 및 멀티 뷰 포트 렌더링 (VR에 유용)과 같은 옵션 기능에 대한 지원은 {vkGetPhysicalDeviceFeatures}[``vkGetPhysicalDeviceFeatures``]를 사용하여 쿼리 할 수 있습니다.

[source,cpp]
----
VkPhysicalDeviceFeatures deviceFeatures;
vkGetPhysicalDeviceFeatures(device, &deviceFeatures);
----

나중에 장치 메모리 및 {queuef}에 대해 논의할 장치에서 쿼리할 수 있는 자세한 내용이 있습니다(다음 섹션 참조).

예를 들어, 지오메트리 셰이더를 지원하는 전용 그래픽 카드에만 사용할 수 있는 응용 프로그램을 고려한다고 가정해 보겠습니다. 그런 다음 ``isDeviceSuitable`` 함수는 다음과 같습니다.

[source,cpp]
----
bool isDeviceSuitable(VkPhysicalDevice device) {
    VkPhysicalDeviceProperties deviceProperties;
    VkPhysicalDeviceFeatures deviceFeatures;
    vkGetPhysicalDeviceProperties(device, &deviceProperties);
    vkGetPhysicalDeviceFeatures(device, &deviceFeatures);

    return deviceProperties.deviceType == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU && deviceFeatures.geometryShader;
}
----

장치가 적합한지 여부를 확인하고 첫 번째 장치와 함께 가는 대신 각 장치에 점수를 부여하고 가장 높은 장치를 선택할 수도 있습니다. 그렇게 하면 더 높은 점수를 부여하여 전용 그래픽 카드를 선호할 수 있지만 사용 가능한 유일한 GPU인 경우 통합 GPU로 돌아갑니다. 다음과 같이 구현할 수 있습니다.

[source,cpp]
----
#include <map>
...
void pickPhysicalDevice() {
    ...
    std::multimap<int, VkPhysicalDevice> candidates;

    for (const auto& device : devices) {
        int score = rateDeviceSuitablility(device);
        candidates.insert(std::make_pair(score, device));
    }

    if (candidates.rbegin()->first > 0) {
        _physicalDevice = candidates.rbegin()->second;
    } else {
        throw std::runtime_error("failed to find a suitable GPU!");
    }
}

int rateDeviceSuitablility(VkPhysicalDevice device) {
    ...
    int score = 0;

    if (deviceProperties.deviceType == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU) {
        score += 1000;
    }

    score += deviceProperties.limits.maxImageDemension2D;

    if (!deviceFeatures.geometryShader) {
        return 0;
    }

    return score;
}
----

이 자습서를 위해 모든 것을 구현할 필요는 없지만 장치 선택 프로세스를 설계하는 방법에 대한 아이디어를 제공합니다. 물론 선택의 이름을 표시하고 사용자가 선택할 수도 있습니다.

이제 막 시작했기 때문에 {vk} 지원은 필요한 유일한 것이므로 GPU에만 정착합니다.

[source,cpp]
----
bool isDeviceSuitable(VkPhysicalDevice device) {
    return true;
}
----

다음 섹션에서는 확인해야 할 첫 번째 실제 필수 기능에 대해 논의합니다.

== {queuef}

{vk}의 거의 모든 작업이 그리기에서 텍스처 업로드에 이르기까지 모든 것에 대해 간략하게 언급되어 대기열에 명령을 제출해야합니다. 다른 {queuef}에서 시작하는 다양한 유형의 대기열이 있으며 각 대기열 제품군은 명령의 하위 집합만 허용합니다. 예를 들어, 컴퓨팅 명령의 처리만 허용하는 큐 패밀리 또는 메모리 전송 관련 명령만 허용하는 큐 패밀리가 있을 수 있습니다.

우리는 어떤 {queuef}이 장치에서 지원되는지, 그리고 이들 중 하나가 우리가 사용하고자 하는 명령을 지원하는지 확인해야 합니다. 이를 위해 필요한 모든 {queue}을 찾는 새로운 기능 ``findQueueFamilies``를 추가합니다.

지금 우리는 그래픽 명령을 지원하는 {queue}만 찾고 있으므로 함수는 다음과 같습니다.

[source,cpp]
----
uint32_t findQueueFamilies(VkPhysicalDevice device) {

}
----

그러나 다음 챕터 중 하나에서 우리는 이미 또 다른 대기열을 찾을 것이므로 이에 대비하고 인덱스를 구조대로 묶는 것이 좋습니다.

[source,cpp]
----
struct QueueFamilyIndices {
    uint32_t graphicsFamily;
}

QueueFamilyIndices findQueueFamilies(VkPhysicalDevice device) {
    QueueFamilyIndices indices;

    return indices;
}
----

그러나 {queuef}을 사용할 수 없는 경우 어떻게 해야합니까? 우리는 ``findQueueFamilies``에서 예외를 던질 수 있지만,이 기능은 실제로 장치 적합성에 대한 결정을 내리는 데 적합한 장소가 아닙니다. 예를 들어, 전용 전송 대기열 제품군이 있는 장치를 선호할 수 있지만 필요하지는 않습니다. 따라서 특정 {queuef}이 발견되었는지 여부를 나타내는 방법이 필요합니다.

``uint32_t``의 값은 이론적으로 ``0``을 포함한 유효한 {queuef} 지수가 될 수 있기 때문에 숫자 값의 문자열을 사용하여 {queuef}의 존재하지 않음을 나타내는 것은 실제로 불가능합니다. 운 좋게도 C++17은 기존 또는 그렇지 않은 값의 경우를 구별하는 데이터 구조를 도입했습니다.

[source,cpp]
----
#include <optional>
...
std::optional<uint32_t> graphicsFamily;

std::cout << std::boolalpha << graphicsFamily.has_value() << std::endl; // false

graphicsFamily = 0;

std::cout << std::boolalpha << graphicsFamily.has_value() << std::endl; // true
----

``std::optional``는 무언가를 할당할 때까지 값이 없는 래퍼입니다. 어느 시점에서 당신은 값을 포함하는 경우 ``has_value()`` 멤버 함수를 호출하여 쿼리 할 수 있습니다. 즉, 논리를 다음과 같이 변경할 수 있습니다.

[source,cpp]
----
#include <optional>
...
struct QueueFamilyIndices {
    std::optional<uint32_t> graphicsFamily;
}

QueueFamilyIndices findQueueFamilies(VkPhysicalDevice device) {
    QueueFamilyIndices indices;

    return indices;
}
----

이제 ``findQueueFamilies``를 실제로 구현할 수 있습니다.

[source,cpp]
----
QueueFamilyIndices findQueueFamilies(VkPhysicalDevice device) {
    QueueFamilyIndices indices;
    ...

    return indices;
}
----

{queuef} 목록을 검색하는 과정은 정확히 당신이 기대하는 것이며 {vkGetPhysicalDeviceQueueFamilyProperties}[``vkGetPhysicalDeviceQueueFamilyProperties``]를 사용하는 것입니다.

[source,cpp]
----
uint32_t queueFamilyCount = 0;
vkGetPhysicalDeviceQueueFamilyProperties(device, &queueFamilyCount, nullptr);

std::vector<VkQueueFamilyProperties> queueFamilies(queueFamilyCount);
vkGetPhysicalDeviceQueueFamilyProperties(device, &queyeFamilyCount, queueFamilies.data());
----

{VkQueueFamilyProperties}[``VkQueueFamilyProperties``] 구조체에는 지원되는 작업 유형과 해당 {queuef}를 기반으로 만들 수 있는 {queue} 수를 포함하여 {queuef}에 대한 세부 정보가 포함되어 있습니다. ``VK_QUEUE_GRAPHICS_BIT``를 지원하는 최소 하나의 대기열 제품군을 찾아야 합니다.

[source,cpp]
----
int i = 0;

for (const auto& queueFamily: queueFamilies) {
    if (queueFamily.queueFlags & VK_QUEUE_GRAPHICS_BIT) {
        indices.graphicsFamily = i;
    }

    i++;
}
----

이제 이 멋진 {queuef}의 조회 기능이 있으므로 ``isDeviceSuitable`` 함수의 체크인으로 사용하여 장치가 사용하려는 명령을 처리할 수 있도록 할 수 있습니다.

[source,cpp]
----
bool isDeviceSuitable(VkPhysicalDevice device) {
    QueueFamilyIndices = findQueueFamilies(device);

    return indices.graphicsFamily.has_value();
}
----

이것을 조금 더 편리하게 만들기 위해, 우리는 또한 구조 자체에 일반적인 체크를 추가할 것입니다:

[source,cpp]
----
struct QueueFamilyIndices {
    std::optional<uint32_t> graphicsFamily;

    bool isComplte() {
        return graphicsFamily.has_value();
    }
};

...

bool isDeviceSuitable(VkPhysicalDevice device) {
    QueueFamilyIndices = findQueueFamilies(device);

    return indices.isComplete();
}
----

또한 ``findQueueFamilies``에서의 반복문을 조기 종료하기 위해 이것을 사용할 수 있습니다(__We can now also use this for an early exit from ``findQueueFamilies``__):

[source,cpp]
----
for (const auto& queueFamily: queueFamilies) {
    ...
    if (indices.isComplete()) {
        break;
    }

    i++;
}
----

좋습니다. 이제 우리는 사용 가능한 물리장치를 찾을 수 있습니다! 다음 단계는 인터페이스 할 link:./LogicalDeviceAndQueues.html[논리 장치를 만드는 것] 입니다(__Great, that's all we need for now to find the right physical device! The next step is to create a logical device to interface with it__).

.작성자 버전의 전체 소스
[%collapsible]
====
[source,cpp,linenums]
----
//
// Created by JoonHo Son on 2026-05-17.
//
#include <vulkan/vulkan.h>

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <optional>
#include <stdexcept>
#include <vector>

#include "vulkan/vulkan_core.h"

#if !defined(NDEBUG) || defined(_DEBUG)
#define DEBUG_BUILD
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TRACE
#else
#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_INFO
#endif

#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#include <spdlog/spdlog.h>

#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/mat4x4.hpp>
#include <glm/vec4.hpp>

const uint32_t WIDTH = 800;
const uint32_t HEIGHT = 600;

const std::vector<const char*> validationLayers{
    "VK_LAYER_KHRONOS_validation",
};

#ifdef DEBUG_BUILD
const bool enableValidationLayers = true;
#else
const bool enableValidationLayers = false;
#endif

VkResult CreateDebugUtilsMessengerEXT(
    VkInstance instance, const VkDebugUtilsMessengerCreateInfoEXT* pCreateInfo,
    const VkAllocationCallbacks* pAllocator,
    VkDebugUtilsMessengerEXT* pDebugMessenger) {
    auto func = (PFN_vkCreateDebugUtilsMessengerEXT)vkGetInstanceProcAddr(
        instance, "vkCreateDebugUtilsMessengerEXT");

    if (func != nullptr) {
        return func(instance, pCreateInfo, pAllocator, pDebugMessenger);
    } else {
        return VK_ERROR_EXTENSION_NOT_PRESENT;
    }
}

void DestroyDebugUtilsMessengerEXT(VkInstance instance,
                                   VkDebugUtilsMessengerEXT debugMessenger,
                                   const VkAllocationCallbacks* pAllocator) {
    auto func = (PFN_vkDestroyDebugUtilsMessengerEXT)vkGetInstanceProcAddr(
        instance, "vkDestroyDebugUtilsMessengerEXT");

    if (func != nullptr) {
        func(instance, debugMessenger, pAllocator);
    }
}

struct QueueFamilyIndices {
    std::optional<uint32_t> graphicsFamily;

    bool isComplete() { return graphicsFamily.has_value(); }
};

class HelloTriangleApplication {
public:
    void run() {
        initWindow();
        initVulkan();
        mainLoop();
        cleanup();
    }

private:
    GLFWwindow* _window;

    VkInstance _instance;

    VkDebugUtilsMessengerEXT _debugMessenger;

    VkPhysicalDevice _physicalDevice = VK_NULL_HANDLE;

    void initWindow() {
        glfwInit();
        glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
        glfwWindowHint(GLFW_RESIZABLE, GLFW_FALSE);

        _window = glfwCreateWindow(WIDTH, HEIGHT, "Vulkan", nullptr, nullptr);
    }

    void initVulkan() {
        createInstance();
        setupDebugMessenger();
        pickPhysicalDevice();
    }

    void mainLoop() {
        while (!glfwWindowShouldClose(_window)) {
            glfwPollEvents();
        }
    }

    void cleanup() {
        if (enableValidationLayers) {
            DestroyDebugUtilsMessengerEXT(_instance, _debugMessenger, nullptr);
        }

        vkDestroyInstance(_instance, nullptr);
        glfwDestroyWindow(_window);
        glfwTerminate();
    }

    void createInstance() {
        if (enableValidationLayers && !checkValidationLayerSupport()) {
            throw std::runtime_error(
                "validation layers requested, but not available!");
        }

        VkApplicationInfo appInfo{
            .sType = VK_STRUCTURE_TYPE_APPLICATION_INFO,
            .pApplicationName = "Hello Triangle",
            .applicationVersion = VK_MAKE_VERSION(1, 0, 0),
            .pEngineName = "No Engine",
            .engineVersion = VK_MAKE_VERSION(1, 0, 0),
            .apiVersion = VK_API_VERSION_1_0,
        };

        auto extensions = getRequiredExtensions();

        VkInstanceCreateInfo createInfo{
            .sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
            .pApplicationInfo = &appInfo,
            .enabledExtensionCount = static_cast<uint32_t>(extensions.size()),
            .ppEnabledExtensionNames = extensions.data(),
        };

        VkDebugUtilsMessengerCreateInfoEXT debugCreateInfo{};

        if (enableValidationLayers) {
            createInfo.enabledLayerCount =
                static_cast<uint32_t>(validationLayers.size());
            createInfo.ppEnabledLayerNames = validationLayers.data();

            populateDebugMessengerCreateInfo(debugCreateInfo);
            createInfo.pNext =
                (VkDebugUtilsMessengerCreateInfoEXT*)&debugCreateInfo;
        } else {
            createInfo.enabledLayerCount = 0;
            createInfo.pNext = nullptr;
        }

        if (vkCreateInstance(&createInfo, nullptr, &_instance) != VK_SUCCESS) {
            SPDLOG_ERROR("----------------------------------------");
            SPDLOG_ERROR("failed to create instance!");
            SPDLOG_ERROR("----------------------------------------");

            throw std::runtime_error("failed to create instance!");
        }

        for (const auto& extension : extensions) {
            SPDLOG_DEBUG("\t {}", extension);
        }
    }

    void populateDebugMessengerCreateInfo(
        VkDebugUtilsMessengerCreateInfoEXT& createInfo) {
        createInfo = {
            .sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT,
            .messageSeverity = VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT |
                               VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT |
                               VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT,
            .messageType = VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT |
                           VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT |
                           VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT,
            .pfnUserCallback = debugCallback,
        };
    }

    void setupDebugMessenger() {
        if (!enableValidationLayers) {
            return;
        }

        VkDebugUtilsMessengerCreateInfoEXT createInfo;

        populateDebugMessengerCreateInfo(createInfo);

        if (CreateDebugUtilsMessengerEXT(_instance, &createInfo, nullptr,
                                         &_debugMessenger) != VK_SUCCESS) {
            throw std::runtime_error("failed to set up debug messenger!");
        }
    }

    void pickPhysicalDevice() {
        uint32_t deviceCount = 0;
        vkEnumeratePhysicalDevices(_instance, &deviceCount, nullptr);

        if (deviceCount == 0) {
            SPDLOG_ERROR("Vulkan을 지원하는 GPU를 찾을 수 없음.");

            throw std::runtime_error(
                "failed to find GPUs with Vulkan support!");
        }

        std::vector<VkPhysicalDevice> devices(deviceCount);
        vkEnumeratePhysicalDevices(_instance, &deviceCount, devices.data());

        for (const auto& device : devices) {
            if (isDeviceSuitable(device)) {
                _physicalDevice = device;

                break;
            }
        }

        if (physicalDevice == VK_NULL_HANDLE) {
            SPDLOG_ERROR("사용 가능한 GPU를 찾지 못함");

            throw std::runtime_error("failed to find a suitable GPU!");
        }
    }

    bool isDeviceSuitable(VkPhysicalDevice device) {
        QueueFamilyIndices indices = findQueueFamilies(device);

        return indices.isComplete();
    }

    QueueFamilyIndices findQueueFamilies(VkPhysicalDevice device) {
        QueueFamilyIndices indices;
        uint32_t queueFamilyCount = 0;

        vkGetPhysicalDeviceQueueFamilyProperties(device, &queueFamilyCount,
                                                 nullptr);
        std::vector<VkQueueFamilyProperties> queueFamilies(queueFamilyCount);
        vkGetPhysicalDeviceQueueFamilyProperties(device, &queueFamilyCount,
                                                 queueFamilies.data());

        for (uint32_t i = 0; i < queueFamilies.size(); i++) {
            if (queueFamilies[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) {
                indices.graphicsFamily = 1;
            }

            if (indices.isComplete()) {
                break;
            }
        }

        return indices;
    }

    std::vector<const char*> getRequiredExtensions() {
        uint32_t glfwExtensionCount = 0;
        const char** glfwExtensions;
        glfwExtensions = glfwGetRequiredInstanceExtensions(&glfwExtensionCount);

        std::vector<const char*> extensions(
            glfwExtensions, glfwExtensions + glfwExtensionCount);

        if (enableValidationLayers) {
            extensions.push_back(VK_EXT_DEBUG_UTILS_EXTENSION_NAME);
        }

        return extensions;
    }

    bool checkValidationLayerSupport() {
        uint32_t layerCount;
        vkEnumerateInstanceLayerProperties(&layerCount, nullptr);

        std::vector<VkLayerProperties> availableLayers(layerCount);
        vkEnumerateInstanceLayerProperties(&layerCount, availableLayers.data());

        for (const char* layerName : validationLayers) {
            bool layerFound = false;

            for (const auto& layerProperties : availableLayers) {
                if (strcmp(layerName, layerProperties.layerName) == 0) {
                    layerFound = true;

                    break;
                }
            }

            if (!layerFound) {
                return false;
            }
        }

        return true;
    }

    static VKAPI_ATTR VkBool32 VKAPI_CALL debugCallback(
        [[maybe_unused]] VkDebugUtilsMessageSeverityFlagBitsEXT messageSeverity,
        [[maybe_unused]] VkDebugUtilsMessageTypeFlagsEXT messageType,
        const VkDebugUtilsMessengerCallbackDataEXT* pcallbackData,
        [[maybe_unused]] void* pUserData) {
        SPDLOG_ERROR("validation layer: {}", pcallbackData->pMessage);

        return VK_FALSE;
    }
};

int main() {
#ifdef DEBUG_BUILD
    spdlog::set_level(spdlog::level::debug);
    spdlog::set_pattern("[%Y-%m-%d %H:%M:%S.%e] [%l] [%s:%#] %v");
#else
    spdlog::set_level(spdlog::level::info);
#endif
    HelloTriangleApplication app;

    try {
        app.run();
    } catch (const std::exception& e) {
        SPDLOG_ERROR("{}", e.what());

        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
----
====